# Project 1
# Generate Project 1
project4: project4.c shapes.h colors.h particle_fire.h materials.h tornado.h boid.h
	g++ project4.c -o project4 glut32.lib -lopengl32 -lglu32 -lcygwin	
	
eyez: eyez.c
	g++ eyez.c -o eyez glut32.lib -lopengl32 -lglu32 -lcygwin	
	
fish: fish.c
	g++ fish.c -o fish glut32.lib -lopengl32 -lglu32 -lcygwin	
	
clean: 
	rm *.exe